server:
  port: 8230

spring:
  jpa:
    properties:
      hibernate:
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 3
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${balance.datasource.host}/${balance.datasource.name}
    username: ${balance.datasource.username}
    password: ${balance.datasource.password}
    hikari:
      maximum-pool-size: 30
  flyway:
    url: ${balance.datasource.host}/${balance.datasource.name}
    user: ${balance.datasource.username}
    password: ${balance.datasource.password}

balance:
  datasource:
    host: jdbc:postgresql://localhost:5432
    name: solidgate
    username: solid
    password: solid